"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SUBMIT_STATUS_PENDING = exports.SUBMIT_STATUS_FAILURE = exports.SUBMIT_STATUS_SUCCESS = void 0;
var SUBMIT_STATUS_SUCCESS = 'SUBMIT_STATUS_SUCCESS';
exports.SUBMIT_STATUS_SUCCESS = SUBMIT_STATUS_SUCCESS;
var SUBMIT_STATUS_FAILURE = 'SUBMIT_STATUS_FAILURE';
exports.SUBMIT_STATUS_FAILURE = SUBMIT_STATUS_FAILURE;
var SUBMIT_STATUS_PENDING = 'SUBMIT_STATUS_PENDING';
exports.SUBMIT_STATUS_PENDING = SUBMIT_STATUS_PENDING;