'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
/**
 * Created by rouven on 22.03.17.
 */

var PREFIX = '@@wikom-grid/';

var INITIALIZE = exports.INITIALIZE = PREFIX + 'INITIALIZE';
var DESTROY = exports.DESTROY = PREFIX + 'DESTROY';
var DATA_CHANGED = exports.DATA_CHANGED = PREFIX + 'DATA_CHANGED';
var SELECTION_CHANGED = exports.SELECTION_CHANGED = PREFIX + 'SELECTION_CHANGED';
var INITIALIZE_FILTER = exports.INITIALIZE_FILTER = PREFIX + 'INITIALIZE_FILTER';
var DESTROY_FILTER = exports.DESTROY_FILTER = PREFIX + 'DESTROY_FILTER';

var SETNEXTEDITROW = exports.SETNEXTEDITROW = PREFIX + 'SETNEXTEDITROW';
var FIELDCHANGED = exports.FIELDCHANGED = PREFIX + 'FIELDCHANGED';
var FIELDSAVED = exports.FIELDSAVED = PREFIX + 'FIELDSAVED';
var FIELDINSUBMISSION = exports.FIELDINSUBMISSION = PREFIX + 'FIELDINSUBMISSION';
var FIELDSUBMISSIONFAILED = exports.FIELDSUBMISSIONFAILED = PREFIX + 'FIELDSUBMISSIONFAILED';