"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.EDIT_START = exports.DESTROY_FILTER = exports.INITIALIZE_FILTER = exports.SELECTION_CLEARED = exports.SELECTION_CHANGED = exports.DATA_CHANGED = exports.DESTROY = exports.INITIALIZE = void 0;

/**
 * Created by rouven on 22.03.17.
 */
var PREFIX = '@@wikom-grid/';
var INITIALIZE = PREFIX + 'INITIALIZE';
exports.INITIALIZE = INITIALIZE;
var DESTROY = PREFIX + 'DESTROY';
exports.DESTROY = DESTROY;
var DATA_CHANGED = PREFIX + 'DATA_CHANGED';
exports.DATA_CHANGED = DATA_CHANGED;
var SELECTION_CHANGED = PREFIX + 'SELECTION_CHANGED';
exports.SELECTION_CHANGED = SELECTION_CHANGED;
var SELECTION_CLEARED = PREFIX + 'SELECTION_CLEARED';
exports.SELECTION_CLEARED = SELECTION_CLEARED;
var INITIALIZE_FILTER = PREFIX + 'INITIALIZE_FILTER';
exports.INITIALIZE_FILTER = INITIALIZE_FILTER;
var DESTROY_FILTER = PREFIX + 'DESTROY_FILTER';
exports.DESTROY_FILTER = DESTROY_FILTER;
var EDIT_START = PREFIX + 'EDIT_START';
exports.EDIT_START = EDIT_START;